name: zebrautil
description: A plugin for working with zebra printers in flutter
version: 0.0.40
homepage:
repository: https://github.com/anthonyR012/zebra_printer_utility
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebrautilPlugin
      ios:
        pluginClass: ZebrautilPlugin
